### ISSUE TITLE
Compilation failure: "wrong number of arguments (given 3, expected 2)"

### ISSUE THREAD

**Issue by manuel489** [metanorma/isodoc-i18n#2]
````
bundle exec metanorma -t iso -x html sources/iso-13584-42/document.adoc
Fatal Error: wrong number of arguments (given 3, expected 2)
C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-i18n-1.0.5/lib/isodoc/i18n.rb:57:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-iso-2.0.8.1/lib/isodoc/iso/init.rb:19:in `new'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-iso-2.0.8.1/lib/isodoc/iso/init.rb:19:in `i18n_init'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-2.0.7/lib/metanorma/standoc/utils.rb:64:in `isodoc'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-2.0.7/lib/metanorma/standoc/base.rb:90:in `init_i18n'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-2.0.7/lib/metanorma/standoc/base.rb:34:in `init'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-iso-2.0.8.1/lib/metanorma/iso/base.rb:45:in `init'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-2.0.7/lib/metanorma/standoc/base.rb:113:in `document1'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-2.0.7/lib/metanorma/standoc/base.rb:103:in `document'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-2.0.7/lib/metanorma/standoc/utils.rb:13:in `convert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/asciidoctor-2.0.17/lib/asciidoctor/document.rb:955:in `convert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/asciidoctor-2.0.17/lib/asciidoctor/convert.rb:120:in `convert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.4.7.1/lib/metanorma/input/asciidoc.rb:18:in `process'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.4.7.1/lib/metanorma/processor.rb:21:in `input_to_isodoc'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.4.7.1/lib/metanorma/compile.rb:59:in `process_input_adoc'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.4.7.1/lib/metanorma/compile.rb:42:in `process_input'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.4.7.1/lib/metanorma/compile.rb:33:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/compiler.rb:30:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/compiler.rb:35:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/command.rb:241:in `compile_document'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/command.rb:47:in `block in compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/command.rb:47:in `each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli/command.rb:47:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.5.14/lib/metanorma/cli.rb:34:in `start'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.5.14/exe/metanorma:25:in `block in <top (required)>'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.5.14/exe/metanorma:43:in `<top (required)>'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/bin/metanorma:23:in `load'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/bin/metanorma:23:in `<main>'

````

**Comment by opoudjis** [comment]
I am mid-refactor with this. Please wait until Monday release.
